Repository NomadBlacky/scaladog, pull requests merged in 2020-01, with the labels that each got.

#97 Update upickle to 0.9.7
  build.sbt
Labels: dependencies

#96 Update requests to 0.4.9
  build.sbt
Labels: dependencies

#99 Add a helper post single metric to MetricsAPIClient
  build.sbt
  src/main/scala/scaladog/api/metrics/MetricsAPIClient.scala
  src/test/scala/scaladog/ScaladogUnitTest.scala
  src/test/scala/scaladog/api/metrics/MetricsAPIClientImplTest.scala
Labels: enhancement

#100 Update requests to 0.5.0
  build.sbt
Labels: dependencies

#101 Update upickle to 0.9.8
  build.sbt
Labels: dependencies

#102 Update sbt to 1.3.7
  project/build.properties
Labels: dependencies

#103 Update sbt-release to 1.0.13
  project/plugins.sbt
Labels: dependencies

#104 Add the `build` category to release-drafter.yml
  .github/release-drafter.yml
Labels: build

#105 Update mockito-scala-scalatest to 1.10.6
  build.sbt
Labels: dependencies

#106 Update mockito-scala-scalatest to 1.11.0
  build.sbt
Labels: dependencies

#107 Update sbt-scalafmt to 2.3.1
  project/plugins.sbt
Labels: dependencies

#108 Update mockito-scala-scalatest to 1.11.1
  build.sbt
Labels: dependencies
